---
# .readthedocs.yml
# # Read the Docs configuration file
# # See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# # Required
#
version: 2

author: "Open Network Automation Platform"
copyright: "© Copyright ONAP. Licensed under Creative Commons Attribution 4.0 International License."

build:
   image: latest

python:
   version: 3.7
   install:
      - requirements: etc/requirements-docs.txt

submodules:
   include: all

sphinx:
   configuration: docs/conf.py
